# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
      UserBundle\Entity\User: sha512

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
      dbusers:
        id: user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~
            provider: dbusers
            guard:
              authenticators:
                - jwt_authenticator
              entry_point: jwt_authenticator
    access_control:
      - { path: /login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /public_api/*, roles: ROLE_USER }
      - { path: /admin_api/*, roles: ROLE_ADMIN }