services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  controller.user.default:
    class: UserBundle\Controller\DefaultController
    arguments: ['@request_stack','@doctrine.orm.default_entity_manager','@serializer']