services:
  controller.user.security:
    class: UserBundle\Controller\SecurityController
    arguments: ['@service_container']
  user_provider:
    class: UserBundle\Provider\UserProvider
    arguments: ['@doctrine.orm.entity_manager']
  jwt_authenticator:
    class: UserBundle\Authenticator\JwtAuthenticator
    arguments: ["@doctrine.orm.entity_manager","@lexik_jwt_authentication.encoder"]